# SPDX-FileCopyrightText: 2026 Alessandro Gregucci (battread contributions)
# SPDX-License-Identifier: GPL-3.0-or-later

"""Independent wire fixtures for bounded MPR parsing, corruption and lifetimes.

Synthetic records are written with struct, not generated by the decoder being
tested. Galvani comparison is additional evidence; scientific expectations use
known encoded numbers and the separately licensed export in test_biologic.py.
"""

# pyright: reportPrivateUsage=false, reportUnknownMemberType=false, reportUnknownVariableType=false, reportUnknownArgumentType=false

import importlib.util
import struct
from collections.abc import Generator
from io import BytesIO
from pathlib import Path
from typing import BinaryIO, cast

import numpy as np
import pandas as pd
import pytest

import battread.readers.biologic as adapter
import battread.readers.mpr as binary
from battread import convert, inspect, iter_read, read
from battread.exceptions import (
    CorruptedFileError,
    IncompatibleDataError,
    NonMonotonicTimeError,
    UnsupportedFormatError,
)
from battread.warnings import MissingValueWarning

pytestmark = pytest.mark.skipif(
    importlib.util.find_spec("galvani") is None, reason="Install battread[biologic]"
)


def wire_module(
    name: bytes, version: int, payload: bytes, modern: bool = False
) -> bytes:
    """Write a known v1/v2 module header independently of Galvani's definitions."""
    if modern:
        header = struct.pack(
            "<10s25sIIII8s",
            name,
            name,
            0xFFFFFFFF,
            len(payload),
            version,
            11,
            b"01/01/24",
        )
    else:
        header = struct.pack(
            "<10s25sII8s", name, name, len(payload), version, b"01/01/24"
        )
    return b"MODULE" + header + payload


def wire_source(
    path: Path,
    version: int = 2,
    modern: bool = False,
    paired_v0: bool = False,
    times: tuple[float, ...] = (10.0, 11.0, 13.0),
) -> Path:
    """Encode independent time/current/voltage records in supported data layouts."""
    ids = (4, 8, 6)
    initial = struct.pack("<IB", len(times), len(ids))
    if version == 0:
        if paired_v0:
            header = initial + bytes((0, 4, 0, 8, 0, 6))
            header = header.ljust(1007, b"\x00")
        else:
            header = (initial + bytes(ids)).ljust(100, b"\x00")
    else:
        header = initial + struct.pack("<HHH", *ids)
        header = header.ljust(406 if version == 3 else 405, b"\x00")
    records = b"".join(
        struct.pack("<dff", time, -2.0 if index % 2 == 0 else 3.0, 3.5)
        for index, time in enumerate(times)
    )
    path.write_bytes(
        binary.MPR_MAGIC
        + wire_module(b"VMP Set   ", 0, b"", modern)
        + wire_module(b"VMP data  ", version, header + records, modern)
    )
    return path


@pytest.mark.parametrize("modern", [False, True])
@pytest.mark.parametrize(
    "version,paired", [(0, False), (0, True), (2, False), (3, False)]
)
@pytest.mark.parametrize("chunk", [1, 2, 100_000])
def test_known_layouts_match_encoded_values_and_galvani(
    tmp_path: Path, modern: bool, version: int, paired: bool, chunk: int
) -> None:
    """Both module headers and all data versions preserve signs and exact timing."""
    from galvani import BioLogic  # pyright: ignore[reportMissingImports]

    source = wire_source(tmp_path / "synthetic.mpr", version, modern, paired)
    expected = pd.DataFrame(
        {
            "time_s": [0.0, 1.0, 3.0],
            "current_mA": [-2.0, 3.0, -2.0],
            "voltage_V": [3.5] * 3,
        }
    )
    pd.testing.assert_frame_equal(read(source), expected)
    chunks = list(iter_read(source, chunk_size=chunk))
    pd.testing.assert_frame_equal(pd.concat(chunks, ignore_index=True), expected)
    layout = adapter._load_mpr(source)
    actual = np.concatenate(list(layout.iter_arrays(2)))
    with source.open("rb") as stream:
        legacy = BioLogic.MPRfile(stream)
    np.testing.assert_array_equal(actual, legacy.data)


def test_no_full_backend_constructor_is_used(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Inspection and conversion must work when full-memory parsing is forbidden."""
    from galvani import BioLogic  # pyright: ignore[reportMissingImports]

    def forbidden(*args: object, **kwargs: object) -> None:
        """Fail immediately if the old full-acquisition allocation path is invoked."""
        raise AssertionError("Full-memory constructor must not be called")

    monkeypatch.setattr(BioLogic, "MPRfile", forbidden)
    source = wire_source(tmp_path / "bounded.mpr")
    assert inspect(source).reader == "biologic-mpr"
    assert sum(len(frame) for frame in iter_read(source, chunk_size=1)) == 3
    result = convert(source, tmp_path / "result.parquet", chunk_size=1)
    pd.testing.assert_frame_equal(read(result), read(source))
    assert adapter.BioLogicMPRReader.capabilities.streaming


def test_binary_read_counts_are_bounded(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A huge requested chunk cannot disable the binary-byte buffer cap."""
    source = wire_source(
        tmp_path / "bounded.mpr", times=tuple(float(i) for i in range(25))
    )
    layout = adapter._load_mpr(source)
    monkeypatch.setattr(binary, "_MAX_BINARY_BYTES", 3 * layout.dtype.itemsize)
    arrays = list(layout.iter_arrays(1_000_000))
    assert [len(array) for array in arrays] == [3] * 8 + [1]
    assert all(array.nbytes <= 3 * layout.dtype.itemsize for array in arrays)


def test_inspection_reads_only_bounded_metadata(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Inspection must seek over large payloads instead of copying their contents."""
    source = wire_source(tmp_path / "bounded.mpr")
    original = binary._prefix
    requests: list[int] = []

    def counted(stream: BinaryIO, module: binary._Module, length: int) -> bytes:
        """Observe the size of each explicitly bounded metadata prefix request."""
        requests.append(length)
        return original(stream, module, length)

    monkeypatch.setattr(binary, "_prefix", counted)
    inspect(source)
    assert requests == [6, 405]


@pytest.mark.parametrize(
    "mutation",
    ["truncate", "extra", "count", "padding", "duplicate", "tail", "version"],
)
def test_corrupt_container_is_rejected_before_values(
    tmp_path: Path, mutation: str
) -> None:
    """Invalid framing/counts/reserved bytes must never silently omit rows."""
    source = wire_source(tmp_path / "bad.mpr")
    contents = bytearray(source.read_bytes())
    data_header = len(binary.MPR_MAGIC) + 6 + 51 + 6
    data_offset = data_header + 51
    if mutation == "truncate":
        contents = contents[:-1]
    elif mutation == "extra":
        contents += b"\x00"
    elif mutation == "count":
        struct.pack_into("<I", contents, data_offset, 4)
    elif mutation == "padding":
        contents[data_offset + 20] = 1
    elif mutation == "duplicate":
        contents += wire_module(b"VMP Set   ", 0, b"")
    elif mutation == "tail":
        contents += b"MODULE"
    else:
        struct.pack_into("<I", contents, data_header + 39, 99)
    source.write_bytes(contents)
    with pytest.raises(CorruptedFileError):
        inspect(source)


def test_source_mutation_after_inspection_is_rejected(tmp_path: Path) -> None:
    """A replaced/truncated acquisition cannot be read using stale metadata."""
    source = wire_source(tmp_path / "mutable.mpr")
    layout = adapter._load_mpr(source)
    source.write_bytes(source.read_bytes()[:-1])
    with pytest.raises(CorruptedFileError, match="changed"):
        next(layout.iter_arrays(1))


def test_iterator_close_releases_windows_file_handle(tmp_path: Path) -> None:
    """Cancellation after a yielded chunk releases the source for Windows cleanup."""
    source = wire_source(tmp_path / "cancel.mpr")
    iterator = cast(
        Generator[pd.DataFrame, None, None], iter_read(source, chunk_size=1)
    )
    assert len(next(iterator)) == 1
    iterator.close()
    source.unlink()
    assert not source.exists()


def test_late_backward_time_keeps_conversion_atomic(tmp_path: Path) -> None:
    """A late scientific failure must not publish any partially converted file."""
    source = wire_source(tmp_path / "bad-time.mpr", times=(10.0, 11.0, 9.0))
    target = tmp_path / "result.parquet"
    with pytest.raises(NonMonotonicTimeError):
        convert(source, target, chunk_size=1)
    assert not target.exists()


def test_missing_current_is_retained_across_binary_batches(tmp_path: Path) -> None:
    """Missing measured current must remain missing across binary batches."""
    source = wire_source(tmp_path / "missing.mpr")
    contents = bytearray(source.read_bytes())
    current_offset = len(binary.MPR_MAGIC) + 2 * (6 + 51) + 405 + 16 + 8
    struct.pack_into("<f", contents, current_offset, float("nan"))
    source.write_bytes(contents)
    with pytest.warns(MissingValueWarning):
        frames = list(iter_read(source, chunk_size=1))
    assert np.isnan(frames[1].current_mA.iloc[0])
    assert sum(len(frame) for frame in frames) == 3


def test_unknown_215_is_not_guessed_from_record_length(tmp_path: Path) -> None:
    """An upstream-unverified field must fail even when a width might seem plausible."""
    header = (struct.pack("<IBHH", 1, 2, 4, 215)).ljust(405, b"\x00")
    source = tmp_path / "unsupported.mpr"
    source.write_bytes(
        binary.MPR_MAGIC
        + wire_module(b"VMP Set   ", 0, b"")
        + wire_module(b"VMP data  ", 2, header + struct.pack("<df", 0.0, 3.0))
    )
    with pytest.raises(UnsupportedFormatError, match="215"):
        inspect(source)


def test_header_seek_arithmetic_uses_python_ints(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Seeking past large modules must not wrap NumPy uint32 header lengths."""
    offsets: list[int] = []

    class HeaderBackend:
        """Simulate yield-before-seek metadata without allocating a huge file."""

        def read_VMP_modules(
            self, stream: BinaryIO, read_module_data: bool = True
        ) -> Generator[dict[str, object], None, None]:
            """Require normalized integer fields before the generator resumes."""
            assert read_module_data is False
            for name, offset, length in (
                (b"extra", 100, 2**32 - 1),
                (b"VMP Set   ", 2**32 + 200, 0),
                (b"VMP data  ", 2**32 + 300, 0),
            ):
                description: dict[str, object] = {
                    "shortname": name,
                    "offset": offset,
                    "length": np.uint32(length),
                    "version": 0,
                    "date": b"01/01/24",
                }
                yield description
                left, right = description["offset"], description["length"]
                assert isinstance(left, int) and isinstance(right, int)
                offsets.append(left + right)

    def stamp(stream: BinaryIO) -> tuple[int, int, int, int]:
        """Provide virtual large-file bounds without allocating disk space or RAM."""
        return (0, 0, 2**32 + 4096, 0)

    monkeypatch.setattr(binary, "_stamp", stamp)
    modules = binary._metadata(
        BytesIO(binary.MPR_MAGIC), cast(binary.GalvaniSchema, HeaderBackend())
    )
    assert len(modules) == 2
    assert offsets[0] == 2**32 + 99


@pytest.mark.parametrize("size", [0, -1])
def test_invalid_binary_batch_size_cannot_trigger_unbounded_read(
    tmp_path: Path, size: int
) -> None:
    """NumPy's negative-count full-file behavior must never bypass the byte bound."""
    source = wire_source(tmp_path / "bounded.mpr")
    layout = adapter._load_mpr(source)
    with pytest.raises(IncompatibleDataError):
        next(layout.iter_arrays(size))
